In [2]:
print("hola mundo")

hola mundo


In [3]:
import numpy as np 

In [5]:
lista=[1,2,3,4]

In [6]:
array = np.array(lista)

In [7]:
print(array)

[1 2 3 4]


In [8]:
lista2 = [[1,2,3] ,[4,5,6] ,[7,8,9]]

In [14]:
lista2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [15]:
array2 = np.array(lista2)

In [16]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
array3 =np.arange(5)

In [14]:
array3

array([0, 1, 2, 3, 4])

In [16]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [21]:
np.zeros(3)

array([0., 0., 0.])

In [25]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.zeros((5,12))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [28]:
np.ones((5,12))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [20]:
np.linspace(2,10,20)

array([ 2.        ,  2.42105263,  2.84210526,  3.26315789,  3.68421053,
        4.10526316,  4.52631579,  4.94736842,  5.36842105,  5.78947368,
        6.21052632,  6.63157895,  7.05263158,  7.47368421,  7.89473684,
        8.31578947,  8.73684211,  9.15789474,  9.57894737, 10.        ])

In [29]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

NUMEROS ALEATORIOS RAND-RANDN

In [30]:
np.random.rand(5)

array([0.12044394, 0.18065301, 0.19495455, 0.44862912, 0.39594077])

In [31]:
np.random.rand(3,5)

array([[0.0190679 , 0.13527323, 0.43464664, 0.53630845, 0.83711084],
       [0.93531296, 0.87922549, 0.41815881, 0.51282144, 0.46437885],
       [0.26883577, 0.96953541, 0.1293579 , 0.32140665, 0.12624039]])

In [32]:
np.random.randn(3,5)

array([[-1.02128695, -1.60481311, -0.33028049,  1.73757899,  0.78659327],
       [ 1.14686632,  0.22240231, -0.54776143,  2.84281677,  0.79382384],
       [-1.59546477,  1.05920059, -0.22258414, -1.10207118,  1.04661652]])

NÚMEROS ALEATORIOS ENTEROS - RANDINT

In [33]:
np.random.randint(1,20)

1

In [35]:
np.random.randint(1,100,6)

array([27, 85, 34, 13, 44, 36], dtype=int32)

VALOR MAX Y MIN

In [34]:
array4=np.random.randint(1,100,50)
array4

array([77, 20,  6, 45, 58, 80, 54, 69, 23, 72, 42, 79, 35,  5, 30, 58, 90,
       73, 25, 35, 32, 86, 86, 45, 26,  4, 98, 51, 19, 73, 80,  9, 82,  2,
       42, 87, 59, 67, 67, 92, 58, 37, 59, 88, 23, 39, 41, 48, 42, 55],
      dtype=int32)

In [37]:
valor_maximo = array4.max()
valor_maximo

np.int32(98)

In [39]:
pos_valor_max = array4.argmax()
pos_valor_max

np.int64(26)

In [40]:
valor_minimo = array4.min()
valor_minimo

np.int32(2)

In [41]:
pos_valor_min = array4.argmin()
pos_valor_min

np.int64(33)

ARREGLOS 

In [52]:
array5= np.arange(0,10)
array5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])